language: node_js
node_js:
    - 6
    - 7
    - 8
    - 9
    - node
script:
    - npm test
    - npm run lint

# need C++11-compatible compiler to build the weak package
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
