language: node_js
node_js:
    - 6
    - 7
    - 8
    - 9
    - 10
script:
    - npm test
    - npm run lint

env:
  global:
    # need C++11-compatible compiler to build the weak package
    - CXX=g++-4.8
  matrix:
    - EIDER_WS_LIB=uws
    - EIDER_WS_LIB=ws
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
    exclude:
        # uws 9.148.0 fails to compile on node 10
        - node_js: 10
          env: EIDER_WS_LIB=uws
